services:
  backend:
    build:
      context: ./backend
    container_name: logicontrol_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "https://shiny-broccoli-v6w9xwgpr6rvhxrv9-3000.app.github.dev"
    container_name: logicontrol_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend